version: '3.8'

services:
  mcp-router:
    build: 
      context: ./services/mcp-router
      dockerfile: Dockerfile
    container_name: mcp-router
    ports:
      - "3100:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/mcp:/services/mcp:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MCP_SERVICES_PATH=/services/mcp
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp-network:
    driver: bridge
    name: mcp-network